# -*- coding: utf-8 -*-
"""DXPO_MagicBox_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg8UTVsTEiyh4MOid_9-O1Vjk2hrskMw
"""

# ============================================
# DXPO AI MAGIC BOX v2.0
# MASTER STARTUP CELL
# Run this every session!!
# ============================================

# Install

# Imports
import pandas as pd
import numpy as np
from scipy import stats
import plotly.graph_objects as go
import anthropic
import warnings
warnings.filterwarnings('ignore')

# API connection

api_key = userdata.get('ANTHROPIC_API_KEY')
client = anthropic.Anthropic(api_key=api_key)

print("=" * 45)
print("🪄 DXPO AI MAGIC BOX v2.0")
print("=" * 45)
print("✅ Libraries ready!")
print(f"✅ API key: {len(api_key)} chars")
print("✅ Claude client ready!")
print("=" * 45)
print("📂 Now run Cell 2 to upload data!")
print("=" * 45)

# ============================================
# DXPO AI MAGIC BOX v2.0
# By Dr. Jay Rajasekera
# Tokyo International University
# ============================================

# Install libraries
!pip install anthropic plotly kaleido -q

# Import all
import pandas as pd
import numpy as np
from scipy import stats
import plotly.graph_objects as go
import anthropic
import warnings
warnings.filterwarnings('ignore')

# Connect API

api_key = userdata.get('ANTHROPIC_API_KEY')
client = anthropic.Anthropic(api_key=api_key)

print("=" * 45)
print("🪄 DXPO AI MAGIC BOX v2.0")
print("=" * 45)
print("✅ Libraries ready!")
print(f"✅ API key: {len(api_key)} chars")
print("✅ Claude client ready!")
print("=" * 45)

# ============================================
# CELL 2: GENERIC FILE UPLOAD
# Works for ANY Excel or CSV file!!
# ============================================

print("=" * 45)
print("📂 DATA UPLOAD")
print("=" * 45)
print("Upload your company data file")
print("Supported: Excel (.xlsx .xls .xlsm)")
print("           CSV (.csv)")
print("─" * 45)

uploaded = files.upload()
fname = list(uploaded.keys())[0]

# ── Load file ──
if fname.endswith('.csv'):
    df = pd.read_csv(fname)
    print(f"\n✅ CSV loaded: {fname}")

else:
    # Show available sheets
    xl = pd.ExcelFile(fname)
    sheets = xl.sheet_names
    print(f"\nFound {len(sheets)} sheet(s):")
    for i, s in enumerate(sheets, 1):
        print(f"  {i}. {s}")

    if len(sheets) > 1:
        # Let user choose sheet
        sheet_num = input(
            "\nWhich sheet? Enter number: ")
        try:
            sheet = sheets[int(sheet_num)-1]
        except:
            sheet = sheets[0]
    else:
        sheet = sheets[0]

    df = pd.read_excel(fname,
                       sheet_name=sheet)
    print(f"\n✅ Loaded sheet: '{sheet}'")

# ── Auto-detect column types ──
num_cols = df.select_dtypes(
    include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(
    include=['object']).columns.tolist()

# ── Profile ──
print(f"\n📊 DATA PROFILE:")
print(f"   Rows          : {df.shape[0]:,}")
print(f"   Columns       : {df.shape[1]}")
print(f"   Numeric cols  : {len(num_cols)}")
print(f"   Category cols : {len(cat_cols)}")
print(f"   Missing values: "
      f"{df.isnull().sum().sum()}")

print(f"\n📋 COLUMNS DETECTED:")
print(f"   Numeric  : {num_cols[:5]}")
if len(num_cols) > 5:
    print(f"              + {len(num_cols)-5} more")
print(f"   Category : {cat_cols[:5]}")

print("\n" + "=" * 45)
print("✅ Data ready for DXPO DOC!!")
print("=" * 45)

# ============================================
# CELL 3: DXPO DOC v3
# Professional questionnaire
# Primary + Secondary answers!!
# ============================================

print("=" * 55)
print("🏥 DXPO DOC — Business Health Interview")
print("   Dr. Jay Rajasekera · TIU")
print("=" * 55)
print("""
Like Ningendokku — we listen first!!
Please answer 5 questions.
For Q2 and Q3 give PRIMARY
and SECONDARY answers if applicable.
""")

# Q1
print("─" * 55)
print("Q1 of 5 · INDUSTRY")
print("""
  1. 🛒 Retail / E-commerce
  2. 🏭 Manufacturing
  3. 💰 Financial Services
  4. 🏥 Healthcare
  5. 🚚 Logistics / Supply Chain
  6. 🔧 Other
""")
q1 = input("Enter number (1-6): ").strip()
industries = {
    "1":"Retail/E-commerce",
    "2":"Manufacturing",
    "3":"Financial Services",
    "4":"Healthcare",
    "5":"Logistics/Supply Chain",
    "6":"Other"}

# Q2
print("\n" + "─" * 55)
print("Q2 of 5 · MAIN CONCERNS")
print("""
  1. 📉 Revenue declining
  2. 💸 Costs too high
  3. 👥 Losing customers / churn
  4. ⏱️ Processes too slow
  5. 🔍 Cannot identify best customers
  6. 📢 Marketing not effective
""")
q2p = input("PRIMARY concern (1-6): ").strip()
q2s = input(
    "SECONDARY concern (1-6) "
    "or Enter to skip: ").strip()

concerns = {
    "1":"Revenue declining",
    "2":"Costs too high",
    "3":"Losing customers/churn",
    "4":"Processes too slow",
    "5":"Cannot identify best customers",
    "6":"Marketing not effective"}

# Q3
print("\n" + "─" * 55)
print("Q3 of 5 · DEPARTMENT FOCUS")
print("""
  1. 📊 Sales & Marketing
  2. ⚙️  Operations
  3. 💹 Finance
  4. 🤝 Customer Service
  5. 🏢 All equally
""")
q3p = input("PRIMARY dept (1-5): ").strip()
q3s = input(
    "SECONDARY dept (1-5) "
    "or Enter to skip: ").strip()

depts = {
    "1":"Sales & Marketing",
    "2":"Operations",
    "3":"Finance",
    "4":"Customer Service",
    "5":"All equally"}

# Q4
print("\n" + "─" * 55)
print("Q4 of 5 · DATA RECENCY")
print("""
  1. 📅 Last 3 months
  2. 📆 Last 1 year
  3. 🗓️  Last 3 years
  4. 📂 More than 3 years old
  5. ❓ Not sure
""")
q4 = input("Enter number (1-5): ").strip()
data_ages = {
    "1":"Very recent (3 months)",
    "2":"Recent (1 year)",
    "3":"Older (3 years)",
    "4":"Historical (3+ years)",
    "5":"Unknown age"}

# Q5
print("\n" + "─" * 55)
print("Q5 of 5 · PREVIOUS DX ATTEMPTS")
print("""
  1. 🆕 No — first attempt
  2. ❌ Yes — results were poor
  3. ⚡ Yes — partial success
  4. 🔄 Currently in progress
""")
q5 = input("Enter number (1-4): ").strip()
dx_hist = {
    "1":"No previous DX attempts",
    "2":"Previous attempts failed",
    "3":"Partial DX success",
    "4":"DX in progress"}

# Store context
doc_context = {
    "industry"          : industries.get(q1,"Unknown"),
    "concern_primary"   : concerns.get(q2p,"Unknown"),
    "concern_secondary" : concerns.get(q2s,None)
                          if q2s else None,
    "dept_primary"      : depts.get(q3p,"Unknown"),
    "dept_secondary"    : depts.get(q3s,None)
                          if q3s else None,
    "data_age"          : data_ages.get(q4,"Unknown"),
    "dx_history"        : dx_hist.get(q5,"Unknown")
}

# Summary
print("\n" + "=" * 55)
print("🏥 DXPO DOC — Interview Summary")
print("=" * 55)
print(f"  Industry          : "
      f"{doc_context['industry']}")
print(f"  Primary concern   : "
      f"{doc_context['concern_primary']}")
if doc_context['concern_secondary']:
    print(f"  Secondary concern : "
          f"{doc_context['concern_secondary']}")
print(f"  Primary dept      : "
      f"{doc_context['dept_primary']}")
if doc_context['dept_secondary']:
    print(f"  Secondary dept    : "
          f"{doc_context['dept_secondary']}")
print(f"  Data age          : "
      f"{doc_context['data_age']}")
print(f"  DX history        : "
      f"{doc_context['dx_history']}")
print("=" * 55)
print("✅ Interview complete!!")
print("🔬 Running Marketing Dokku next!!")
print("=" * 55)

# ============================================
# CELL 4: MARKETING DOKKU v2
# Adaptive tests based on DOC context!!
# ============================================

print("=" * 55)
print("🔬 MARKETING DOKKU v2")
print(f"   Industry : {doc_context['industry']}")
print(f"   Primary  : {doc_context['concern_primary']}")
if doc_context['concern_secondary']:
    print(f"   Secondary: {doc_context['concern_secondary']}")
print("=" * 55)

# Define amount columns
# Auto-detect from data!!
amt_cols = [c for c in df.columns
            if '-Amt' in c or 'Amt' in c
            or 'amount' in c.lower()
            or 'revenue' in c.lower()
            or 'sales' in c.lower()]

# Fallback if none detected
if not amt_cols:
    amt_cols = df.select_dtypes(
        include=[np.number]).columns.tolist()
    # Remove ID-like columns
    amt_cols = [c for c in amt_cols
                if 'id' not in c.lower()
                and 'qty' not in c.lower()
                and 'frequency' not in c.lower()]

print(f"\n📊 Amount columns detected:")
for c in amt_cols:
    print(f"   → {c}")

# Calculate totals
df['Total-Amt'] = df[amt_cols].sum(axis=1)
df['Products-Bought'] = (
    df[amt_cols] > 0).sum(axis=1)

n = len(df)
pain_points = []

# ── STANDARD TEST 1 ──
print("\n🔬 S-TEST 1: Customer Segmentation")
print("─" * 40)
mean_spend   = df['Total-Amt'].mean()
median_spend = df['Total-Amt'].median()
zero_spend   = (df['Total-Amt']==0).sum()
zero_pct     = zero_spend/n*100

print(f"  Mean spend   : ${mean_spend:,.2f}")
print(f"  Median spend : ${median_spend:,.2f}")
print(f"  Zero spenders: {zero_spend:,} ({zero_pct:.1f}%)")

if zero_pct > 20:
    flag="🔴 RED"; sev=3
    pain_points.append({
        "test":"Customer Segmentation",
        "finding":f"{zero_pct:.1f}% never spent",
        "severity":sev,"flag":flag,"type":"standard"})
elif zero_pct > 10:
    flag="🟡 YELLOW"; sev=2
    pain_points.append({
        "test":"Customer Segmentation",
        "finding":f"{zero_pct:.1f}% never spent",
        "severity":sev,"flag":flag,"type":"standard"})
else:
    flag="🟢 GREEN"
print(f"  Status       : {flag}")

# ── STANDARD TEST 2 ──
print("\n🔬 S-TEST 2: Customer Retention")
print("─" * 40)

# Auto-detect status column
status_col = None
for c in df.columns:
    if 'status' in c.lower():
        status_col = c
        break

if status_col:
    active = (df[status_col]=='Active').sum()
    inactive = (df[status_col]=='Inactive').sum()
    inactive_pct = inactive/n*100
    active_spend = df[
        df[status_col]=='Active'][
        'Total-Amt'].mean()
    inactive_spend = df[
        df[status_col]=='Inactive'][
        'Total-Amt'].mean()
    spend_gap = active_spend - inactive_spend

    print(f"  Active  : {active:,} ({100-inactive_pct:.1f}%)"
          f" avg ${active_spend:,.2f}")
    print(f"  Inactive: {inactive:,} ({inactive_pct:.1f}%)"
          f" avg ${inactive_spend:,.2f}")
    print(f"  Gap     : ${spend_gap:,.2f}")

    if inactive_pct > 30:
        flag="🔴 RED"; sev=3
        pain_points.append({
            "test":"Customer Retention",
            "finding":f"{inactive_pct:.1f}% inactive"
                      f" · ${spend_gap:,.0f} gap",
            "severity":sev,"flag":flag,"type":"standard"})
    elif inactive_pct > 15:
        flag="🟡 YELLOW"; sev=2
        pain_points.append({
            "test":"Customer Retention",
            "finding":f"{inactive_pct:.1f}% inactive"
                      f" · ${spend_gap:,.0f} gap",
            "severity":sev,"flag":flag,"type":"standard"})
    else:
        flag="🟢 GREEN"
    print(f"  Status  : {flag}")
else:
    print("  ⚠️  No status column detected")

# ── STANDARD TEST 3 ──
print("\n🔬 S-TEST 3: Cross-sell Penetration")
print("─" * 40)
single_pct = (df['Products-Bought']==1).sum()/n*100
multi_pct  = (df['Products-Bought']>1).sum()/n*100

print(f"  Single product: {single_pct:.1f}%")
print(f"  Multi product : {multi_pct:.1f}%")

if single_pct > 60:
    flag="🔴 RED"; sev=3
    pain_points.append({
        "test":"Cross-sell Penetration",
        "finding":f"{single_pct:.1f}% single buyers",
        "severity":sev,"flag":flag,"type":"standard"})
elif single_pct > 40:
    flag="🟡 YELLOW"; sev=2
    pain_points.append({
        "test":"Cross-sell Penetration",
        "finding":f"{single_pct:.1f}% single buyers",
        "severity":sev,"flag":flag,"type":"standard"})
else:
    flag="🟢 GREEN"
print(f"  Status        : {flag}")

# ── STANDARD TEST 4 ──
print("\n🔬 S-TEST 4: Digital Channel Gap")
print("─" * 40)

# Auto-detect channel columns
internet_col = None
mail_col = None
for c in df.columns:
    if 'internet' in c.lower():
        internet_col = c
    if 'mail' in c.lower():
        mail_col = c

if internet_col:
    internet_pct = (df[internet_col]>0).sum()/n*100
    mail_pct = (df[mail_col]>0).sum()/n*100 \
               if mail_col else 0
    print(f"  Internet: {internet_pct:.1f}%")
    print(f"  Mail    : {mail_pct:.1f}%")

    if internet_pct < 10:
        flag="🔴 RED"; sev=3
        pain_points.append({
            "test":"Digital Channel Gap",
            "finding":f"Only {internet_pct:.1f}%"
                      f" ordering online",
            "severity":sev,"flag":flag,
            "type":"standard"})
    elif internet_pct < 25:
        flag="🟡 YELLOW"; sev=2
        pain_points.append({
            "test":"Digital Channel Gap",
            "finding":f"Only {internet_pct:.1f}%"
                      f" ordering online",
            "severity":sev,"flag":flag,
            "type":"standard"})
    else:
        flag="🟢 GREEN"
    print(f"  Status  : {flag}")
else:
    print("  ⚠️  No channel columns detected")

# ── STANDARD TEST 5: Revenue Concentration ──
print("\n🔬 S-TEST 5: Revenue Concentration")
print("─" * 40)

rev_by_prod = {}
for c in amt_cols:
    prod = c.replace('-Amt','')
    rev_by_prod[prod] = df[c].sum()

total_rev = sum(rev_by_prod.values())

# Sort by revenue
sorted_prods = sorted(
    rev_by_prod.items(),
    key=lambda x: x[1],
    reverse=True)

# Show top 3 products
print(f"  Revenue breakdown:")
cumulative = 0
top_prods = []
for prod, rev in sorted_prods[:5]:
    pct = rev/total_rev*100
    cumulative += pct
    print(f"  → {prod}: "
          f"${rev:,.0f} ({pct:.1f}%)")
    if pct > 15:
        top_prods.append(
            f"{prod} ({pct:.1f}%)")

# Top product
top_prod = sorted_prods[0][0]
top_pct  = sorted_prods[0][1]/total_rev*100

# Top 3 combined
top3_pct = sum(
    r/total_rev*100
    for _,r in sorted_prods[:3])

finding = (
    f"Top products: "
    f"{', '.join(top_prods)}"
    f" = {top3_pct:.1f}% of revenue")

print(f"\n  {finding}")

if top_pct > 40:
    flag="🔴 RED"; sev=3
    pain_points.append({
        "test"    : "Revenue Concentration",
        "finding" : finding,
        "severity": sev,
        "flag"    : flag,
        "type"    : "standard"})
elif top_pct > 25:
    flag="🟡 YELLOW"; sev=2
    pain_points.append({
        "test"    : "Revenue Concentration",
        "finding" : finding,
        "severity": sev,
        "flag"    : flag,
        "type"    : "standard"})
else:
    flag="🟢 GREEN"
print(f"  Status: {flag}")

# ── ADAPTIVE TESTS ──
print("\n\n📋 ADAPTIVE TESTS")
print("─" * 55)
adaptive_run = []

# Churn adaptive test
churn_triggers = [
    "Losing customers/churn",
    "Cannot identify best customers",
    "Revenue declining",
    "Marketing not effective"
]
if (doc_context['concern_primary']
    in churn_triggers or
    doc_context.get('concern_secondary')
    in churn_triggers):

    print("\n🔬 A-TEST: Churn Risk")
    adaptive_run.append("Churn Risk")

    if status_col:
        rev_at_risk = inactive * inactive_spend
        recovery   = rev_at_risk * 0.5
        inact_pct_of_act = (
            inactive_spend/active_spend*100)

        print(f"  Inactive spend vs Active: "
              f"{inact_pct_of_act:.1f}%")
        print(f"  Revenue at risk: "
              f"${rev_at_risk:,.2f}")
        print(f"  Recovery (50%): "
              f"${recovery:,.2f}")

        if inact_pct_of_act < 60:
            flag="🔴 RED"; sev=3
            pain_points.append({
                "test":"Churn Risk",
                "finding":f"${rev_at_risk:,.0f}"
                          f" revenue at risk",
                "severity":sev,"flag":flag,
                "type":"adaptive"})
        else:
            flag="🟡 YELLOW"; sev=2
            pain_points.append({
                "test":"Churn Risk",
                "finding":f"${rev_at_risk:,.0f}"
                          f" at risk",
                "severity":sev,"flag":flag,
                "type":"adaptive"})
        print(f"  Status: {flag}")

# Customer value adaptive test
value_triggers = [
    "Sales & Marketing",
    "Customer Service"
]
if (doc_context['dept_primary']
    in value_triggers or
    doc_context.get('dept_secondary')
    in value_triggers):

    print("\n🔬 A-TEST: Customer Value Distribution")
    adaptive_run.append("Customer Value")

    top10 = df['Total-Amt'].quantile(0.90)
    top10_rev = df[
        df['Total-Amt']>=top10][
        'Total-Amt'].sum()
    top10_pct = top10_rev/total_rev*100

    print(f"  Top 10% spend >${top10:,.0f}+")
    print(f"  Top 10% = {top10_pct:.1f}% revenue")

    if top10_pct > 50:
        flag="🔴 RED"; sev=3
        pain_points.append({
            "test":"Customer Value Distribution",
            "finding":f"Top 10% = {top10_pct:.1f}%"
                      f" of revenue",
            "severity":sev,"flag":flag,
            "type":"adaptive"})
    elif top10_pct > 35:
        flag="🟡 YELLOW"; sev=2
        pain_points.append({
            "test":"Customer Value Distribution",
            "finding":f"Top 10% = {top10_pct:.1f}%"
                      f" of revenue",
            "severity":sev,"flag":flag,
            "type":"adaptive"})
    else:
        flag="🟢 GREEN"
    print(f"  Status: {flag}")

# ── SUMMARY ──
red_pts = [p for p in pain_points
           if p['flag']=='🔴 RED']
yel_pts = [p for p in pain_points
           if p['flag']=='🟡 YELLOW']

print("\n\n" + "=" * 55)
print("🏥 MARKETING DOKKU — DIAGNOSIS")
print("=" * 55)
print(f"\n  Standard tests: 5")
print(f"  Adaptive tests: {len(adaptive_run)}")
print(f"  Total tests   : {5+len(adaptive_run)}")
print(f"\n  🔴 RED    : {len(red_pts)}")
for p in red_pts:
    t = "STD" if p['type']=='standard' else "ADP"
    print(f"     [{t}] {p['test']}: {p['finding']}")
print(f"\n  🟡 YELLOW : {len(yel_pts)}")
for p in yel_pts:
    t = "STD" if p['type']=='standard' else "ADP"
    print(f"     [{t}] {p['test']}: {p['finding']}")
print(f"\n  Total pain points: {len(pain_points)}")
print("=" * 55)
print("✅ Marketing Dokku complete!!")
print("🎯 Ready for Impact Evaluation!!")
print("=" * 55)

# ============================================
# CELL 5: DXPO IMPACT EVALUATION
# Figure 4 · Dr. Jay Rajasekera
# A × B = Impact!!
# ============================================

print("=" * 55)
print("🎯 DXPO IMPACT EVALUATION")
print("   Figure 4 · Dr. Jay Rajasekera")
print("   APO Framework · Springer")
print("=" * 55)
print("""
For each pain point:
  A: Customer Value (1-10)
     How valuable is solving this?
  B: Implementation Potential (1-10)
     Can your company solve this?
     10 = full internal capability
      1 = needs full external help
  Impact = A × B
""")

impact_scores = []

for i, p in enumerate(pain_points, 1):
    print(f"\n{'─'*45}")
    print(f"Pain Point {i}: {p['test']}")
    print(f"Finding : {p['finding']}")
    print(f"Flag    : {p['flag']}")
    print()

    while True:
        try:
            a = int(input(
                "  A — Customer Value (1-10): "))
            if 1 <= a <= 10:
                break
            print("  ⚠️  Enter 1-10!")
        except:
            print("  ⚠️  Numbers only!")

    while True:
        try:
            b = int(input(
                "  B — Implementation "
                "Potential (1-10): "))
            if 1 <= b <= 10:
                break
            print("  ⚠️  Enter 1-10!")
        except:
            print("  ⚠️  Numbers only!")

    impact = a * b
    impact_scores.append({
        "pain_point"              : p['test'],
        "finding"                 : p['finding'],
        "flag"                    : p['flag'],
        "customer_value"          : a,
        "implementation_potential": b,
        "impact"                  : impact
    })
    print(f"  ✅ Impact = {a} × {b} = {impact}")

# Sort + rank
impact_scores.sort(
    key=lambda x: x['impact'],
    reverse=True)
for i, p in enumerate(impact_scores, 1):
    p['rank'] = i

# Display table
print("\n\n" + "=" * 55)
print("📊 DXPO IMPACT TABLE")
print("=" * 55)
print(f"\n{'Process':<28} {'A':>4} "
      f"{'B':>4} {'Impact':>8} {'Rank':>6}")
print("─" * 55)

for p in impact_scores:
    icon = ("🥇" if p['rank']==1 else
            "🥈" if p['rank']==2 else
            "🥉" if p['rank']==3 else
            f"#{p['rank']}")
    print(f"{p['pain_point']:<28} "
          f"{p['customer_value']:>4} "
          f"{p['implementation_potential']:>4} "
          f"{p['impact']:>8} {icon:>6}")

print("─" * 55)
print(f"\n🥇 TOP PRIORITY: "
      f"{impact_scores[0]['pain_point']}")
print(f"   Impact = {impact_scores[0]['impact']}")
print("\n✅ Impact Evaluation complete!!")
print("🎯 Ready for Plotly Objects!!")

# ============================================
# CELL 6: PLOTLY OBJECTS
# Crystal Ball style — downloadable!!
# ============================================

import plotly.graph_objects as go


# ── OBJECT 3: Impact Table ──
processes = [p['pain_point']
             for p in impact_scores]
a_scores  = [p['customer_value']
             for p in impact_scores]
b_scores  = [p['implementation_potential']
             for p in impact_scores]
impacts   = [p['impact']
             for p in impact_scores]
ranks     = [f"#{p['rank']}"
             for p in impact_scores]

colors = ['#2ECC71' if i>=70 else
          '#F39C12' if i>=50 else
          '#E74C3C' for i in impacts]

fig3 = go.Figure(data=[go.Table(
    columnwidth=[280,70,70,90,70],
    header=dict(
        values=[
            '<b>Process / Pain Point</b>',
            '<b>A<br>Customer<br>Value</b>',
            '<b>B<br>Implementation<br>Potential</b>',
            '<b>Impact<br>A × B</b>',
            '<b>Rank</b>'],
        fill_color='#1B3A6B',
        font=dict(color='white',
                  size=12,
                  family='Arial'),
        align='center',
        height=50),
    cells=dict(
        values=[processes, a_scores,
                b_scores, impacts, ranks],
        fill_color=[
            ['#F8F9FA']*len(processes),
            ['#EBF5FB']*len(processes),
            ['#EBF5FB']*len(processes),
            colors,
            ['#F8F9FA']*len(processes)],
        font=dict(
            color=[
                ['#1B3A6B']*len(processes),
                ['#1B3A6B']*len(processes),
                ['#1B3A6B']*len(processes),
                ['white']*len(processes),
                ['#1B3A6B']*len(processes)],
            size=12, family='Arial'),
        align='center',
        height=38)
)])

fig3.update_layout(
    title=dict(
        text='🎯 DXPO Impact Evaluation Table<br>'
             '<sup>Figure 4 · Dr. Jay Rajasekera'
             ' · APO Framework · Springer</sup>',
        x=0.5,
        font=dict(size=16, color='#1B3A6B')),
    height=350,
    margin=dict(l=20,r=20,t=80,b=30),
    paper_bgcolor='white')

fig3.show()
fig3.write_html('DXPO_Object3_ImpactTable.html')
files.download('DXPO_Object3_ImpactTable.html')

# ── OBJECT 4: Roadmap ──
roadmap_data = []
timeline_map = {
    "🔴 RED"   : ("Immediate", "#E74C3C", 0, 1),
    "🟡 YELLOW": ("Short Term", "#F39C12", 1, 2)
}

for i, p in enumerate(impact_scores):
    phase, color, start, dur = \
        timeline_map.get(
            p['flag'],
            ("Medium Term","#95A5A6",2,2))
    roadmap_data.append({
        "name" : p['pain_point'],
        "phase": phase,
        "color": color,
        "start": start,
        "dur"  : dur
    })

fig4 = go.Figure()
for r in roadmap_data:
    fig4.add_trace(go.Bar(
        y=[r['name']],
        x=[r['dur']],
        base=[r['start']],
        orientation='h',
        marker_color=r['color'],
        marker_line=dict(
            color='white', width=1),
        text=r['phase'],
        textposition='inside',
        insidetextanchor='middle',
        showlegend=False))

fig4.update_layout(
    title=dict(
        text='📅 DXPO Implementation Roadmap<br>'
             '<sup>Based on Impact Rankings · '
             'Dr. Jay Rajasekera</sup>',
        x=0.5,
        font=dict(size=16, color='#1B3A6B')),
    xaxis=dict(
        title='Timeline (Months)',
        tickvals=[0,1,2,3,4],
        ticktext=['Now','M1','M2','M3','M4'],
        gridcolor='#EEEEEE'),
    yaxis=dict(autorange='reversed'),
    barmode='overlay',
    plot_bgcolor='#FAFAFA',
    paper_bgcolor='white',
    height=380,
    margin=dict(l=20,r=20,t=80,b=60))

fig4.show()
fig4.write_html('DXPO_Object4_Roadmap.html')
files.download('DXPO_Object4_Roadmap.html')

# ── OBJECT 5: Revenue KPIs ──
fig5 = go.Figure(data=[go.Table(
    columnwidth=[300,200],
    header=dict(
        values=['<b>KPI</b>','<b>Value</b>'],
        fill_color='#1B3A6B',
        font=dict(color='white',
                  size=13,family='Arial'),
        align='center', height=45),
    cells=dict(
        values=[
            ['Total Revenue',
             'Revenue at Risk (Churn)',
             'Recovery Potential (50%)',
             'Digital Channel Opportunity'],
            [f"${df['Total-Amt'].sum():,.0f}",
             f"${inactive*inactive_spend:,.0f}",
             f"${inactive*inactive_spend*0.5:,.0f}",
             f"{100-internet_pct:.1f}% untapped"]
        ],
        fill_color=[
            ['#EBF5FB','#FDEDEC',
             '#FEF9E7','#EAFAF1'],
            ['#EBF5FB','#FDEDEC',
             '#FEF9E7','#EAFAF1']],
        font=dict(
            color=[
                ['#1B3A6B']*4,
                ['#1B3A6B',
                 '#E74C3C',
                 '#F39C12',
                 '#2ECC71']],
            size=[12,15],
            family='Arial'),
        align=['left','center'],
        height=45)
)])

fig5.update_layout(
    title=dict(
        text='💰 DXPO Revenue Intelligence<br>'
             '<sup>Key Performance Indicators · '
             'Dr. Jay Rajasekera</sup>',
        x=0.5,
        font=dict(size=16, color='#1B3A6B')),
    height=320,
    margin=dict(l=20,r=20,t=80,b=20),
    paper_bgcolor='white')

fig5.show()
fig5.write_html('DXPO_Object5_KPIs.html')
files.download('DXPO_Object5_KPIs.html')

print("✅ All Plotly Objects built!!")
print("📥 3 files downloaded!!")
print("   → Object 3: Impact Table")
print("   → Object 4: Roadmap")
print("   → Object 5: Revenue KPIs")
print("\n🎯 Ready for Claude DXPO Report!!")

# ============================================
# CELL 7: CLAUDE DXPO NARRATIVE REPORT
# ============================================

print("=" * 55)
print("🪄 GENERATING DXPO REPORT...")
print("=" * 55)

# Build summary for Claude
summary = f"""
COMPANY: {doc_context['industry']}
CONCERN: {doc_context['concern_primary']}
DEPT: {doc_context['dept_primary']}
DATA: {doc_context['data_age']}
DX HISTORY: {doc_context['dx_history']}

PAIN POINTS FOUND ({len(pain_points)}):
"""
for p in impact_scores:
    summary += f"""
  #{p['rank']} {p['pain_point']}
  Finding: {p['finding']}
  Impact Score: {p['impact']}/100
  (A={p['customer_value']} ×
   B={p['implementation_potential']})
"""

message = client.messages.create(
    model="claude-opus-4-5",
    max_tokens=1500,
    messages=[{"role": "user",
               "content": f"""
You are the DXPO AI Magic Box by
Dr. Jay Rajasekera,
Tokyo International University.

DXPO = Digital Transformation-driven
Process Optimization

Based on this analysis:
{summary}

Generate a concise professional
DXPO report with:

1. EXECUTIVE SUMMARY
2. TOP 3 PAIN POINTS
3. RECOMMENDED DX APPROACH
4. QUICK WINS (30 days)
5. STRATEGIC ROADMAP (6 months)

Board-level · Concise · Actionable!!
"""}])

report = message.content[0].text

print(report)
print("\n" + "=" * 55)
print("✅ DXPO Report generated!!")

# Save report
with open('DXPO_Report_v2.txt','w') as f:
    f.write(report)
files.download('DXPO_Report_v2.txt')
print("📥 Report downloaded!!")

2+2

# Quick check before Cell 7
try:
    print(f"✅ Data: {df.shape}")
    print(f"✅ impact_scores: {len(impact_scores)}")
    print(f"✅ doc_context: {doc_context['industry']}")
    print(f"✅ client ready")
    print("🚀 Ready for Cell 7!!")
except NameError as e:
    print(f"⚠️  Missing: {e}")

# ============================================
# CELL 7: CLAUDE DXPO NARRATIVE REPORT
# ============================================

print("=" * 55)
print("🪄 GENERATING DXPO REPORT...")
print("=" * 55)

summary = f"""
COMPANY: {doc_context['industry']}
CONCERN: {doc_context['concern_primary']}
DEPT: {doc_context['dept_primary']}
DATA: {doc_context['data_age']}
DX HISTORY: {doc_context['dx_history']}

PAIN POINTS FOUND ({len(pain_points)}):
"""
for p in impact_scores:
    summary += f"""
  #{p['rank']} {p['pain_point']}
  Finding: {p['finding']}
  Impact Score: {p['impact']}/100
"""

message = client.messages.create(
    model="claude-opus-4-5",
    max_tokens=1500,
    messages=[{"role": "user",
               "content": f"""
You are the DXPO AI Magic Box by
Dr. Jay Rajasekera,
Tokyo International University.

DXPO = Digital Transformation-driven
Process Optimization

Based on this analysis:
{summary}

Generate a concise professional
DXPO report with:

1. EXECUTIVE SUMMARY
2. TOP 3 PAIN POINTS
3. RECOMMENDED DX APPROACH
4. QUICK WINS (30 days)
5. STRATEGIC ROADMAP (6 months)

Board-level · Concise · Actionable!!
"""}])

report = message.content[0].text
print(report)

# Save and download
with open('DXPO_Report_v2.txt','w') as f:
    f.write(report)
files.download('DXPO_Report_v2.txt')
print("\n✅ Report generated!!")
print("📥 Downloaded to your PC!!")

# Verify all cells ran successfully
try:
    print(f"✅ Data: {df.shape}")
    print(f"✅ Pain points: {len(pain_points)}")
    print(f"✅ Impact scores: {len(impact_scores)}")
    print(f"✅ Client ready")
    print("🚀 Ready to build dxpo_app.py!!")
except NameError as e:
    print(f"⚠️  Missing: {e}")

# ============================================
# BUILD dxpo_app.py — Complete v2
# ============================================

app_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import anthropic
import os
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="DXPO AI Magic Box",
    page_icon="🪄",
    layout="wide"
)

st.title("DXPO AI Magic Box")
st.subheader(
    "Dr. Jay Rajasekera | "
    "Tokyo International University")
st.markdown("---")

# ── STEP INDICATORS ──
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.info("**Step 1**\\n\\n🏥 DXPO DOC Interview")
with col2:
    st.info("**Step 2**\\n\\n📂 Upload Data")
with col3:
    st.info("**Step 3**\\n\\n🔬 Marketing Dokku")
with col4:
    st.info("**Step 4**\\n\\n📊 DXPO Report")
st.markdown("---")

# ── DXPO DOC INTERVIEW ──
st.subheader("🏥 Step 1 — DXPO DOC Interview")
st.caption(
    "Like Ningendokku — we listen first!!")

col1, col2 = st.columns(2)

with col1:
    industry = st.radio(
        "Q1: Your industry?",
        ["🛒 Retail/E-commerce",
         "🏭 Manufacturing",
         "💰 Financial Services",
         "🏥 Healthcare",
         "🚚 Logistics/Supply Chain",
         "🔧 Other"])

    concern_options = [
        "📉 Revenue declining",
        "💸 Costs too high",
        "👥 Losing customers/churn",
        "⏱️ Processes too slow",
        "🔍 Cannot identify best customers",
        "📢 Marketing not effective"]

    concern_primary = st.selectbox(
        "Q2: PRIMARY concern:",
        concern_options)

    concern_secondary = st.selectbox(
        "Q2: SECONDARY concern (optional):",
        ["None"] + concern_options)

with col2:
    dept_options = [
        "📊 Sales & Marketing",
        "⚙️ Operations",
        "💹 Finance",
        "🤝 Customer Service",
        "🏢 All equally"]

    dept_primary = st.selectbox(
        "Q3: PRIMARY department:",
        dept_options)

    dept_secondary = st.selectbox(
        "Q3: SECONDARY department (optional):",
        ["None"] + dept_options)

    data_age = st.radio(
        "Q4: Data recency?",
        ["📅 Last 3 months",
         "📆 Last 1 year",
         "🗓️ Last 3 years",
         "📂 More than 3 years",
         "❓ Not sure"])

    dx_history = st.radio(
        "Q5: Previous DX attempts?",
        ["🆕 No — first attempt",
         "❌ Previous attempts failed",
         "⚡ Partial success",
         "🔄 In progress"])

doc_context = {
    "industry"          : industry,
    "concern_primary"   : concern_primary,
    "concern_secondary" : concern_secondary
                          if concern_secondary != "None"
                          else None,
    "dept_primary"      : dept_primary,
    "dept_secondary"    : dept_secondary
                          if dept_secondary != "None"
                          else None,
    "data_age"          : data_age,
    "dx_history"        : dx_history
}

st.markdown("---")

# ── FILE UPLOAD ──
st.subheader("📂 Step 2 — Upload Your Data")

uploaded_file = st.file_uploader(
    "Upload Excel or CSV file",
    type=["xlsx","xls","xlsm","csv"])

if uploaded_file is not None:
    try:
        if uploaded_file.name.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
            st.success(
                f"✅ Loaded: {uploaded_file.name}")
        else:
            xl = pd.ExcelFile(uploaded_file)
            sheets = xl.sheet_names
            if len(sheets) > 1:
                sheet = st.selectbox(
                    "Select sheet:",
                    sheets)
            else:
                sheet = sheets[0]
            df = pd.read_excel(
                uploaded_file,
                sheet_name=sheet)
            st.success(
                f"✅ Loaded sheet: {sheet}")

        # Profile
        col1,col2,col3,col4 = st.columns(4)
        with col1:
            st.metric("Rows",
                f"{df.shape[0]:,}")
        with col2:
            st.metric("Columns",
                df.shape[1])
        with col3:
            st.metric("Missing",
                df.isnull().sum().sum())
        with col4:
            num_cols = df.select_dtypes(
                include=[np.number]
                ).columns.tolist()
            st.metric("Numeric Cols",
                len(num_cols))

        with st.expander("👀 Preview Data"):
            st.dataframe(
                df.head(10),
                use_container_width=True)

        st.markdown("---")

        # ── RUN ANALYSIS ──
        if st.button(
            "🔬 Run Marketing Dokku + "
            "Generate DXPO Report!!",
            type="primary",
            use_container_width=True):

            with st.spinner(
                "🪄 Analyzing... "
                "Please wait..."):

                # Detect columns
                amt_cols = [
                    c for c in df.columns
                    if "-Amt" in c or
                    "Amt" in c or
                    "amount" in c.lower()]

                if not amt_cols:
                    amt_cols = [
                        c for c in
                        df.select_dtypes(
                        include=[np.number]
                        ).columns
                        if "id" not in
                        c.lower()]

                df["Total-Amt"] = (
                    df[amt_cols].sum(axis=1))
                df["Products-Bought"] = (
                    df[amt_cols]>0
                    ).sum(axis=1)

                n = len(df)
                pain_points = []

                # Status column
                status_col = None
                for c in df.columns:
                    if "status" in c.lower():
                        status_col = c
                        break

                # Internet column
                internet_col = None
                for c in df.columns:
                    if "internet" in c.lower():
                        internet_col = c
                        break

                # Run tests
                zero_pct = (
                    df["Total-Amt"]==0
                    ).sum()/n*100

                if zero_pct > 20:
                    pain_points.append({
                        "test":"Customer Segmentation",
                        "finding":f"{zero_pct:.1f}% never spent",
                        "flag":"🔴 RED","sev":3})
                elif zero_pct > 10:
                    pain_points.append({
                        "test":"Customer Segmentation",
                        "finding":f"{zero_pct:.1f}% never spent",
                        "flag":"🟡 YELLOW","sev":2})

                if status_col:
                    inactive = (
                        df[status_col]=="Inactive"
                        ).sum()
                    inactive_pct = inactive/n*100
                    active_spend = df[
                        df[status_col]=="Active"][
                        "Total-Amt"].mean()
                    inactive_spend = df[
                        df[status_col]=="Inactive"][
                        "Total-Amt"].mean()
                    spend_gap = (
                        active_spend - inactive_spend)

                    if inactive_pct > 30:
                        pain_points.append({
                            "test":"Customer Retention",
                            "finding":f"{inactive_pct:.1f}% inactive · ${spend_gap:,.0f} gap",
                            "flag":"🔴 RED","sev":3})
                    elif inactive_pct > 15:
                        pain_points.append({
                            "test":"Customer Retention",
                            "finding":f"{inactive_pct:.1f}% inactive · ${spend_gap:,.0f} gap",
                            "flag":"🟡 YELLOW","sev":2})

                if internet_col:
                    internet_pct = (
                        df[internet_col]>0
                        ).sum()/n*100
                    if internet_pct < 10:
                        pain_points.append({
                            "test":"Digital Channel Gap",
                            "finding":f"Only {internet_pct:.1f}% ordering online",
                            "flag":"🔴 RED","sev":3})
                    elif internet_pct < 25:
                        pain_points.append({
                            "test":"Digital Channel Gap",
                            "finding":f"Only {internet_pct:.1f}% ordering online",
                            "flag":"🟡 YELLOW","sev":2})

                # Revenue concentration
                rev_by_prod = {
                    c.replace("-Amt",""):
                    df[c].sum()
                    for c in amt_cols}
                total_rev = sum(
                    rev_by_prod.values())
                sorted_prods = sorted(
                    rev_by_prod.items(),
                    key=lambda x: x[1],
                    reverse=True)
                top_pct = (
                    sorted_prods[0][1]/
                    total_rev*100)
                finding = (
                    "Top 3: " +
                    ", ".join([
                        f"{p}({r/total_rev*100:.1f}%)"
                        for p,r in
                        sorted_prods[:3]]))

                if top_pct > 40:
                    pain_points.append({
                        "test":"Revenue Concentration",
                        "finding":finding,
                        "flag":"🔴 RED","sev":3})
                elif top_pct > 25:
                    pain_points.append({
                        "test":"Revenue Concentration",
                        "finding":finding,
                        "flag":"🟡 YELLOW","sev":2})

                # ── SHOW DIAGNOSIS ──
                st.markdown("---")
                st.subheader(
                    "🔬 Step 3 — Marketing Dokku")

                red_pts = [p for p in pain_points
                           if "RED" in p["flag"]]
                yel_pts = [p for p in pain_points
                           if "YELLOW" in p["flag"]]

                col1, col2 = st.columns(2)
                with col1:
                    st.metric(
                        "🔴 RED Flags",
                        len(red_pts))
                with col2:
                    st.metric(
                        "🟡 YELLOW Flags",
                        len(yel_pts))

                for p in pain_points:
                    st.write(
                        f"{p['flag']} "
                        f"**{p['test']}**: "
                        f"{p['finding']}")

                # ── IMPACT SCORES ──
                st.markdown("---")
                st.subheader(
                    "🎯 Step 4 — DXPO Report")

                # Build impact scores
                impact_scores = []
                for i, p in enumerate(
                        pain_points, 1):
                    col1, col2 = st.columns(2)
                    with col1:
                        a = st.slider(
                            f"A — Customer Value: "
                            f"{p['test']}",
                            1, 10, 7,
                            key=f"a_{i}")
                    with col2:
                        b = st.slider(
                            f"B — Implementation: "
                            f"{p['test']}",
                            1, 10, 5,
                            key=f"b_{i}")
                    impact_scores.append({
                        "pain_point": p["test"],
                        "finding"   : p["finding"],
                        "flag"      : p["flag"],
                        "customer_value": a,
                        "implementation_potential": b,
                        "impact"    : a*b
                    })

                impact_scores.sort(
                    key=lambda x: x["impact"],
                    reverse=True)
                for i,p in enumerate(
                        impact_scores,1):
                    p["rank"] = i

                # ── PLOTLY TABLE ──
                processes = [p["pain_point"]
                    for p in impact_scores]
                a_vals = [p["customer_value"]
                    for p in impact_scores]
                b_vals = [p["implementation_potential"]
                    for p in impact_scores]
                impacts = [p["impact"]
                    for p in impact_scores]
                ranks = [f"#{p['rank']}"
                    for p in impact_scores]

                colors = [
                    "#2ECC71" if i>=70 else
                    "#F39C12" if i>=50 else
                    "#E74C3C"
                    for i in impacts]

                fig = go.Figure(data=[
                    go.Table(
                        columnwidth=[
                            260,70,70,90,70],
                        header=dict(
                            values=[
                                "<b>Pain Point</b>",
                                "<b>A</b>",
                                "<b>B</b>",
                                "<b>Impact</b>",
                                "<b>Rank</b>"],
                            fill_color="#1B3A6B",
                            font=dict(
                                color="white",
                                size=12),
                            align="center",
                            height=40),
                        cells=dict(
                            values=[
                                processes,
                                a_vals,
                                b_vals,
                                impacts,
                                ranks],
                            fill_color=[
                                ["#F8F9FA"]*
                                len(processes),
                                ["#EBF5FB"]*
                                len(processes),
                                ["#EBF5FB"]*
                                len(processes),
                                colors,
                                ["#F8F9FA"]*
                                len(processes)],
                            font=dict(
                                color=[
                                    ["#1B3A6B"]*
                                    len(processes),
                                    ["#1B3A6B"]*
                                    len(processes),
                                    ["#1B3A6B"]*
                                    len(processes),
                                    ["white"]*
                                    len(processes),
                                    ["#1B3A6B"]*
                                    len(processes)],
                                size=12),
                            align="center",
                            height=35))])

                fig.update_layout(
                    title=dict(
                        text="🎯 DXPO Impact Table · "
                             "Dr. Jay Rajasekera",
                        x=0.5,
                        font=dict(
                            size=14,
                            color="#1B3A6B")),
                    height=300,
                    margin=dict(
                        l=10,r=10,t=60,b=10))

                st.plotly_chart(
                    fig,
                    use_container_width=True)

                # Download impact table
                fig.write_html(
                    "DXPO_ImpactTable.html")
                with open(
                    "DXPO_ImpactTable.html",
                    "rb") as f:
                    st.download_button(
                        "📥 Download Impact Table",
                        f,
                        "DXPO_ImpactTable.html",
                        use_container_width=True)

                # ── CLAUDE REPORT ──
                summary = f"""
Company: {doc_context["industry"]}
Concern: {doc_context["concern_primary"]}
Pain points: {len(pain_points)}
"""
                for p in impact_scores:
                    summary += (
                        f"#{p['rank']} "
                        f"{p['pain_point']}: "
                        f"Impact={p['impact']}/100\\n")

                try:
                    api_key = os.environ.get(
                        "ANTHROPIC_API_KEY","")
                    client = anthropic.Anthropic(
                        api_key=api_key)
                    message = client.messages.create(
                        model="claude-opus-4-5",
                        max_tokens=1500,
                        messages=[{
                            "role":"user",
                            "content":f"""
You are DXPO AI Magic Box by
Dr. Jay Rajasekera,
Tokyo International University.

Generate professional DXPO report:
{summary}

Include:
1. EXECUTIVE SUMMARY
2. TOP 3 PAIN POINTS
3. RECOMMENDED DX APPROACH
4. QUICK WINS (30 days)
5. STRATEGIC ROADMAP (6 months)

Board-level · Concise · Actionable!!
"""}])
                    report = (
                        message.content[0].text)
                except Exception as e:
                    report = f"""
## DXPO Analysis Report
Pain points found: {len(pain_points)}
Top priority: {impact_scores[0]["pain_point"]}
*Connect API for full report*
"""

                st.markdown("---")
                st.subheader("🪄 DXPO Report")
                st.markdown(report)

                # Download report
                st.download_button(
                    "📥 Download DXPO Report",
                    report,
                    "DXPO_Report.txt",
                    use_container_width=True)

                st.success(
                    "✅ Analysis complete!!")
                st.balloons()

    except Exception as e:
        st.error(f"❌ Error: {e}")

# ── FOOTER ──
st.markdown("---")
st.caption(
    "🪄 DXPO AI Magic Box | "
    "Dr. Jay Rajasekera | "
    "Tokyo International University | "
    "Powered by Claude AI")
'''

with open('dxpo_app.py', 'w') as f:
    f.write(app_code)

print("✅ dxpo_app.py created!!")
print("🌐 Ready to upload to GitHub!!")
print()
print("New features:")
print("→ Radio buttons for Q1 Q4 Q5")
print("→ Dropdowns for Q2 Q3")
print("→ Primary + Secondary answers")
print("→ Generic file upload")
print("→ Sheet selector")
print("→ Marketing Dokku auto-detect")
print("→ Sliders for A·B scoring")
print("→ Plotly Impact Table")
print("→ Download buttons")
print("→ Claude DXPO Report")

import os

# Verify file exists first
if os.path.exists('dxpo_app.py'):
    size = os.path.getsize('dxpo_app.py')
    print(f"✅ File found: {size:,} bytes")
   
    print("📥 Download started!")
    print("Check your Downloads folder!")
else:
    print("⚠️  File not found!")
    print("Need to run the creation cell again!")

# Write clean dxpo_app.py for Streamlit
app_code = """
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import anthropic
import os
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="DXPO AI Magic Box",
    page_icon="🪄",
    layout="wide"
)

st.title("DXPO AI Magic Box")
st.subheader(
    "Dr. Jay Rajasekera | "
    "Tokyo International University")
st.markdown("---")

# File upload
st.subheader("📂 Upload Your Data")
uploaded_file = st.file_uploader(
    "Upload Excel or CSV file",
    type=["xlsx","xls","xlsm","csv"])

if uploaded_file is not None:
    try:
        if uploaded_file.name.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        else:
            xl = pd.ExcelFile(uploaded_file)
            sheets = xl.sheet_names
            if len(sheets) > 1:
                sheet = st.selectbox(
                    "Select sheet:", sheets)
            else:
                sheet = sheets[0]
            df = pd.read_excel(
                uploaded_file,
                sheet_name=sheet)

        st.success(f"✅ Loaded: {uploaded_file.name}")

        col1,col2,col3 = st.columns(3)
        with col1:
            st.metric("Rows", f"{df.shape[0]:,}")
        with col2:
            st.metric("Columns", df.shape[1])
        with col3:
            st.metric("Missing",
                df.isnull().sum().sum())

        with st.expander("👀 Preview Data"):
            st.dataframe(df.head(10),
                use_container_width=True)

        st.markdown("---")
        st.subheader("🏥 DXPO DOC Interview")

        col1, col2 = st.columns(2)
        with col1:
            industry = st.radio(
                "Q1: Your industry?",
                ["🛒 Retail/E-commerce",
                 "🏭 Manufacturing",
                 "💰 Financial Services",
                 "🏥 Healthcare",
                 "🚚 Logistics/Supply Chain",
                 "🔧 Other"])

            concern_options = [
                "📉 Revenue declining",
                "💸 Costs too high",
                "👥 Losing customers/churn",
                "⏱️ Processes too slow",
                "🔍 Cannot identify best customers",
                "📢 Marketing not effective"]

            concern_primary = st.selectbox(
                "Q2: PRIMARY concern:",
                concern_options)

            concern_secondary = st.selectbox(
                "Q2: SECONDARY concern:",
                ["None"] + concern_options)

        with col2:
            dept_options = [
                "📊 Sales & Marketing",
                "⚙️ Operations",
                "💹 Finance",
                "🤝 Customer Service",
                "🏢 All equally"]

            dept_primary = st.selectbox(
                "Q3: PRIMARY department:",
                dept_options)

            dept_secondary = st.selectbox(
                "Q3: SECONDARY department:",
                ["None"] + dept_options)

            data_age = st.radio(
                "Q4: Data recency?",
                ["📅 Last 3 months",
                 "📆 Last 1 year",
                 "🗓️ Last 3 years",
                 "📂 More than 3 years",
                 "❓ Not sure"])

            dx_history = st.radio(
                "Q5: Previous DX attempts?",
                ["🆕 No — first attempt",
                 "❌ Previous attempts failed",
                 "⚡ Partial success",
                 "🔄 In progress"])

        st.markdown("---")

        if st.button(
            "🔬 Run Marketing Dokku + "
            "Generate DXPO Report!!",
            type="primary",
            use_container_width=True):

            with st.spinner(
                "🪄 Analyzing... Please wait..."):

                amt_cols = [
                    c for c in df.columns
                    if "-Amt" in c or
                    "Amt" in c or
                    "amount" in c.lower()]

                if not amt_cols:
                    amt_cols = [
                        c for c in
                        df.select_dtypes(
                        include=[np.number]
                        ).columns
                        if "id" not in c.lower()]

                df["Total-Amt"] = (
                    df[amt_cols].sum(axis=1))
                n = len(df)
                pain_points = []

                status_col = None
                for c in df.columns:
                    if "status" in c.lower():
                        status_col = c
                        break

                internet_col = None
                for c in df.columns:
                    if "internet" in c.lower():
                        internet_col = c
                        break

                if status_col:
                    inactive = (
                        df[status_col]=="Inactive"
                        ).sum()
                    inactive_pct = inactive/n*100
                    active_spend = df[
                        df[status_col]=="Active"][
                        "Total-Amt"].mean()
                    inactive_spend = df[
                        df[status_col]=="Inactive"][
                        "Total-Amt"].mean()

                    if inactive_pct > 15:
                        pain_points.append({
                            "test":"Customer Retention",
                            "finding":f"{inactive_pct:.1f}% inactive",
                            "flag":"🟡 YELLOW"})

                if internet_col:
                    internet_pct = (
                        df[internet_col]>0
                        ).sum()/n*100
                    if internet_pct < 10:
                        pain_points.append({
                            "test":"Digital Channel Gap",
                            "finding":f"Only {internet_pct:.1f}% online",
                            "flag":"🔴 RED"})

                rev_by_prod = {
                    c.replace("-Amt",""):
                    df[c].sum()
                    for c in amt_cols}
                total_rev = sum(
                    rev_by_prod.values())
                sorted_prods = sorted(
                    rev_by_prod.items(),
                    key=lambda x: x[1],
                    reverse=True)
                top_pct = (
                    sorted_prods[0][1]/
                    total_rev*100)
                finding = (
                    "Top 3: " +
                    ", ".join([
                        f"{p}({r/total_rev*100:.1f}%)"
                        for p,r in sorted_prods[:3]]))
                if top_pct > 25:
                    pain_points.append({
                        "test":"Revenue Concentration",
                        "finding": finding,
                        "flag":"🟡 YELLOW"})

                st.markdown("---")
                st.subheader("🔬 Marketing Dokku Results")

                for p in pain_points:
                    st.write(
                        f"{p['flag']} "
                        f"**{p['test']}**: "
                        f"{p['finding']}")

                st.markdown("---")
                st.subheader("🎯 Impact Scoring")

                impact_scores = []
                for i, p in enumerate(
                        pain_points, 1):
                    col1, col2 = st.columns(2)
                    with col1:
                        a = st.slider(
                            f"A — Value: {p['test']}",
                            1, 10, 7,
                            key=f"a_{i}")
                    with col2:
                        b = st.slider(
                            f"B — Potential: {p['test']}",
                            1, 10, 5,
                            key=f"b_{i}")
                    impact_scores.append({
                        "pain_point": p["test"],
                        "finding"   : p["finding"],
                        "flag"      : p["flag"],
                        "customer_value": a,
                        "implementation_potential": b,
                        "impact"    : a*b
                    })

                impact_scores.sort(
                    key=lambda x: x["impact"],
                    reverse=True)
                for i,p in enumerate(
                        impact_scores,1):
                    p["rank"] = i

                processes = [p["pain_point"]
                    for p in impact_scores]
                a_vals = [p["customer_value"]
                    for p in impact_scores]
                b_vals = [p["implementation_potential"]
                    for p in impact_scores]
                impacts = [p["impact"]
                    for p in impact_scores]
                ranks = [f"#{p['rank']}"
                    for p in impact_scores]
                colors = [
                    "#2ECC71" if i>=70 else
                    "#F39C12" if i>=50 else
                    "#E74C3C"
                    for i in impacts]

                fig = go.Figure(data=[
                    go.Table(
                        header=dict(
                            values=[
                                "<b>Pain Point</b>",
                                "<b>A</b>",
                                "<b>B</b>",
                                "<b>Impact</b>",
                                "<b>Rank</b>"],
                            fill_color="#1B3A6B",
                            font=dict(
                                color="white",
                                size=12),
                            align="center"),
                        cells=dict(
                            values=[
                                processes,
                                a_vals,
                                b_vals,
                                impacts,
                                ranks],
                            fill_color=[
                                ["#F8F9FA"]*len(processes),
                                ["#EBF5FB"]*len(processes),
                                ["#EBF5FB"]*len(processes),
                                colors,
                                ["#F8F9FA"]*len(processes)],
                            font=dict(
                                color=[
                                    ["#1B3A6B"]*len(processes),
                                    ["#1B3A6B"]*len(processes),
                                    ["#1B3A6B"]*len(processes),
                                    ["white"]*len(processes),
                                    ["#1B3A6B"]*len(processes)],
                                size=12),
                            align="center",
                            height=35))])

                fig.update_layout(
                    title=dict(
                        text="🎯 DXPO Impact Table",
                        x=0.5),
                    height=300,
                    margin=dict(l=10,r=10,t=60,b=10))

                st.plotly_chart(
                    fig,
                    use_container_width=True)

                summary = f"Company: {industry}\\n"
                for p in impact_scores:
                    summary += (
                        f"#{p['rank']} "
                        f"{p['pain_point']}: "
                        f"Impact={p['impact']}/100\\n")

                try:
                    api_key = os.environ.get(
                        "ANTHROPIC_API_KEY","")
                    client = anthropic.Anthropic(
                        api_key=api_key)
                    message = client.messages.create(
                        model="claude-opus-4-5",
                        max_tokens=1500,
                        messages=[{
                            "role":"user",
                            "content":f\"\"\"
You are DXPO AI Magic Box by
Dr. Jay Rajasekera,
Tokyo International University.

Generate professional DXPO report:
{summary}

Include:
1. EXECUTIVE SUMMARY
2. TOP 3 PAIN POINTS
3. RECOMMENDED DX APPROACH
4. QUICK WINS (30 days)
5. STRATEGIC ROADMAP (6 months)
\"\"\"}])
                    report = message.content[0].text
                except Exception as e:
                    report = f"API Error: {e}"

                st.markdown("---")
                st.subheader("🪄 DXPO Report")
                st.markdown(report)

                st.download_button(
                    "📥 Download Report",
                    report,
                    "DXPO_Report.txt",
                    use_container_width=True)

                st.success("✅ Analysis complete!!")
                st.balloons()

    except Exception as e:
        st.error(f"❌ Error: {e}")

st.markdown("---")
st.caption(
    "🪄 DXPO AI Magic Box | "
    "Dr. Jay Rajasekera | "
    "Tokyo International University | "
    "Powered by Claude AI")
"""

with open('dxpo_app.py', 'w') as f:
    f.write(app_code)

print("✅ Clean dxpo_app.py created!")
print("   No !pip install")
print("   No google.colab imports")
print("   Uses os.environ for API key")

